### ISSUE TITLE
rearrangements reconciliation

### ISSUE THREAD

**Issue by laserson** [airr-community/airr-formats#33] opened 2017-09-09 18:00 UTC
So it appears the yaml file has been replicated from the `specs/` directory into the Python package itself, which I think is a bit of an anti-pattern, as they are already diverged.  We should figure out a packaging mechanism so the file exists in only the top level `specs/` dir.  Main question for me regarding reconciliation:

Is `fwr1_end` necessary when there is also `cdr1_start`?  Are there ever situations where these are not the exact same?  Same for `cdr1_end`, `fwr2_end`, `cdr2_end`, `fwr3_end`, `fwr4_start`.

**Comment by laserson** [comment] 2017-09-09 18:00
cc @javh @schristley

**Comment by laserson** [comment] 2017-09-09 18:01
Also, just want to confirm that we want both `duplicate_count` and `consensus_count`.

**Comment by laserson** [comment] 2017-09-09 18:03
Also, I suspect we should change `cdr3_start` etc for `junction_start` etc.

**Comment by laserson** [comment] 2017-09-09 18:10
Some reconciliation here: be6c934

**Comment by laserson** [comment] 2017-09-10 16:52
alternatively, we could allow the specs to be replicated in different formats, if that's deemed useful, as long as we set up some continuous integration to check that they're always consistent.

**Comment by javh** [comment] 2017-09-10 17:22
### Specs

Hrm. Do we want to keep `setup.py` where it is or move it to the top level? We can probably just make one of these changes to `setup.py`, depending:

```
package_data={'airr': ['../../specs/*.yaml']}
package_dir={'airr-formats': 'lang/python/airr'}
```

(I didn't test it. Syntax might be off.)

### Count columns

We probably need both `duplicate_count` and `consensus_count`, given how common UMIs are these days. I'm not sure on the naming. I just propagated these from changeo. These two columns are capturing three concepts though:

1. Number of reads contributing to a UMI consensus sequence (`consensus_count`).
2. Number of UMIs sharing an identical sequence (`duplicate_count`).
3. Number of duplicate of a sequence, absent UMI considerations (`duplicate_count`).

The last two are distinguished by context. I think that's okay, but it is a little unclear.

### Position columns

As for duplicating `fwr1_end` with `cdr1_start`, etc... I guess you could have a rare case whether there is an indel exactly at the boundary.  It also depends upon how we want to handle truncated sequences. Ie, do we want to report `fwr1_end` for sequences without an `fwr1_start`, just so we have a `cdr1_start`?

Mostly, I just think it's awkward and confusing to exclude them. You'd be introducing  a `+1` into the code for each region you want to pull.

### junction_start

We might need both? I'm not sure. The FWR/CDR start/end columns seem like separate optional entities to me, especially because they are unnecessary for IMGT-numbered sequences.

**Comment by laserson** [comment] 2017-09-10 17:27
> You'd be introducing a +1 into the code for each region you want to pull.

How so?  With the zero-based half-open scheme, the `fwr1_end` and `cdr1_start` would be the exact same number when extracting slices from the sequence.

**Comment by javh** [comment] 2017-09-10 17:28
Oh, yeah. I forgot about that thing we just talked about. Good point.

**Comment by javh** [comment] 2017-09-10 17:40
Are we planning to write an R package for the format as well? If so, do we want to have the package transform all the positional information into 1-based, closed intervals as part process of importing into R?

**Comment by laserson** [comment] 2017-09-10 17:43
Generally, I'd say it would be nice to have an R package as well.  That said, we should discuss what we want any of our software packages to actually do.  We chose tab-delim format in large part because it's trivially readable with pandas or into a data.frame, so to some extent, we don't really need to write a parser etc. I guess the question is whether we want to design in-memory representations of rearrangements in the different languages.  But it's not obvious to me that there's an advantage there, since any analytics on a list of custom objects will probably be slower than analytics on data frames.

**Comment by javh** [comment] 2017-09-10 17:59
Yeah, I agree we'd be wandering away from the purpose if we try to build a non-tabular representation into the packages. It'd probably be over-engineering too, because I imagine most people would stick with a data frame. I guess what do we *need* right now that we can't get from using a standard parser?

Maybe these?

1. Validating the presence of mandatory columns.
2. Meta-data support.
3. Explicit type conversion.
4. Indexing scheme conversion.

**Comment by matsen** [comment] 2017-09-11 12:16
I think that a basic validator in both languages would be excellent. This would just involve @javh 's 1 above and simple checks about type.

I'm not saying the other bits aren't important, but a validator seems like a part of defining a format.

**Comment by javh** [comment] 2017-09-11 17:09
Hrm. Okay, if we want to do an R package as well then we'll need to have the specs in the R package directory somehow, maybe even as a data object.

I guess we could have a script that propagates, and possibly parses and converts, the specifications in the top level `/specs` folder to the packages in `/lang`.  Having to manually update the package specs seems clunky to me, but might not be so bad. Especially if the packages aren't perfectly in sync w.r.t. features.

**Closed as completed** 2017-10-18 16:01 UTC
